---
- name: Install BA Client
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  roles:
    - role: ibm.storage_protect.ba_client_install
      vars:
        ba_client_state: "absent"
...
