# roles/storage_agent_config/defaults/main.yml
stg_agent_name: ""
stg_agent_password: ""
stg_agent_server_name: ""
stg_agent_hl_add: ""
lladdress: "1502"
server_tcp_port: "1500"
server_hl_address: ""
server_password: ""
stg_agent_path_name: ""
stg_agent_path_dest: "drive"
library: ""
device: ""
copygroup_domain: ""
copygroup_policyset: ""
copygroup_mngclass: ""
copygroup_destination: ""
validate_lan_free: false
node_name: ""
stg_pool: ""
validation_agent_name: ""
