- name: Run DB2 Restore from TSM
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  vars:
    db2_operation: "restore"
    db2_database: ""
    db2_instance: ""
    db2_user: ""
    db2_password: ""
    db2_restore_into: ""        # Optional: restore into different db name
    db2_restore_replace_existing: true       # Replace existing db during restore
    db2_restore_tablespaces: []               # Empty means all tablespaces
    db2_restore_parallelism: 4                # Number of parallel threads
    db2_restore_encrypt: false                 # Decrypt backup if encrypted
    db2_restore_rollforward: true              # Rollforward after restore
  roles:
    - dp_db2_manage
