---
- name: Check current Python version
  ansible.builtin.command: python3 -V
  register: python_version_output
  ignore_errors: true

- name: Print current Python version
  ansible.builtin.debug:
    msg: "Current Python version: {{ python_version_output.stdout | default('Not found') }}"

- name: Set fact for current Python version
  ansible.builtin.set_fact:
    current_python_version: "{{ python_version_output.stdout.split(' ')[1] | default('0.0') }}"

- name: Download and install Python from source
  ansible.builtin.shell: |
    cd /usr/src
    wget {{ python_source_url }}
    tar xzf {{ python_source_filename }}
    cd {{ python_source_dir }}
    ./configure --enable-optimizations
    make altinstall
  args:
    creates: "{{ python_bin_path }}"
  when: current_python_version is version(required_python_version, '<')



