---
galaxy_info:
  role_name: ibm_storage_protect_schedule
  author: YourName
  description: "Ansible role to manage IBM Storage Protect schedules."
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: RedHat
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies: []
