[sp_server_windows]
win1 ansible_host=vanhalen-vm95.storage.tucson.ibm.com

[sp_server_windows:vars]
ansible_connection=winrm
ansible_user=Administrator
ansible_password="Skier%77duhlate"
ansible_port=5985
ansible_python_interpreter="C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python313\\python.exe"

[sp_server_linux]
lin1 ansible_host=bonjovi-vm170.storage.tucson.ibm.com

[sp_server_linux:vars]
ansible_connection=ssh
ansible_user=root
ansible_password="Dandy!43gasbolt"
ansible_python_interpreter="/usr/bin/python3"

[sp_server_aix]
aix1 ansible_host=p9c-vm37.storage.tucson.ibm.com

[sp_server_aix:vars]
ansible_connection=ssh
ansible_user=root
ansible_password="Bonus%68muckoak"
ansible_python_interpreter="/usr/bin//python3"