---
# ==== if state == "present" ===
# 1) check if the binary exists on the control node
# 2) checks whether the system is compatible or not
# 3) query the installed version of SP Server on remote vms and dynamically performs the installation or upgrade
- name: Performing pre-checks before installing Sp Server
  ansible.builtin.include_tasks: sp_server_prechecks.yml
  when: sp_server_state == "present" or sp_server_state == "upgrade"

- name: Install Sp Server
  ansible.builtin.include_tasks: sp_server_install_linux.yml
  when: sp_server_action is defined and sp_server_action == "install"

- name: Upgrade Sp Server
  ansible.builtin.include_tasks: sp_server_upgrade_linux.yml
  when: sp_server_action is defined and sp_server_action == "upgrade"

- name: Uninstall Sp server
  ansible.builtin.include_tasks: sp_server_uninstall_linux.yml
  when: sp_server_state == "absent"

- name: Configure SP Server
  ansible.builtin.include_tasks: sp_server_configuration_linux.yml
  when: sp_server_state == "configure"

...
