- name: Execute command to list installed packages on the remote VM
  ansible.builtin.command:
    cmd: 'sudo {{ imcl_path }} listInstalledPackages'
  register: imcl_output
  changed_when: false
  become: true
  ignore_errors: true

- name: Creating a list of installed packages
  ansible.builtin.set_fact:
    sp_server_installed_components: "{{ imcl_output.stdout_lines }}"
  when: imcl_output is defined

- name: Check if the sp server package is installed
  ansible.builtin.set_fact:
    sp_server_installation_status: true
  when:
    - imcl_output is defined
    - "'com.tivoli.dsm.server' in imcl_output.stdout_lines"
