- name: Kill all dsmserv processes
  ansible.builtin.shell: "pkill -f dsmserv"
  ignore_errors: true

- name: Stop the DB2 instance
  ansible.builtin.shell: "su - {{ tsm_user }} -c 'db2stop'"
  ignore_errors: true

- name: Remove the TSM database
  ansible.builtin.shell: "echo 'y' | su - {{ tsm_user }} -c 'dsmserv removedb {{ sp_server_db_directory }}'"
  ignore_errors: true

- name: Drop the DB2 instance
  ansible.builtin.shell: "{{ db2_instance_path }}/db2idrop {{ tsm_user }}"
  ignore_errors: true

- name: Remove the TSM user
  ansible.builtin.user:
    name: "{{ tsm_user }}"
    state: absent
    remove: true
  ignore_errors: true

- name: Remove the TSM group
  ansible.builtin.group:
    name: "{{ tsm_group }}"
    state: absent
  ignore_errors: true

- name: Remove user-related directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/home/{{ tsm_user }}"
    - "/export/home/{{ tsm_user }}"
    - "/var/spool/mail/{{ tsm_user }}"
    - "/etc/tivoli/tsm/instanceList.obj"
  ignore_errors: true
