clean_up: false
instance_dir: "/tsminst1"
storage_prepare_size: "xsmall"

allowed_sizes:
  - xsmall
  - small
  - medium
  - large

dsk_size:
  xsmall:
    TSMdbspace: [200, 250]
    TSMalog: [30, 80]
    TSMarchlog: [251, 300]
    TSMfile: [10000, 10050]
    TSMbkup: [1000, 1050]
  small:
    TSMdbspace: [1000, 1050]
    TSMalog: [140, 190]
    TSMarchlog: [1000, 1005]
    TSMfile: [38000, 38050]
    TSMbkup: [3000, 3050]
  medium:
    TSMdbspace: [2000, 2005]
    TSMalog: [140, 190]
    TSMarchlog: [2000, 2005]
    TSMfile: [180000, 180050]
    TSMbkup: [10000, 10050]
  large:
    TSMdbspace: [4000, 4050]
    TSMalog: [550, 600]
    TSMarchlog: [4000, 4050]
    TSMfile: [500000, 500050]
    TSMbkup: [16000, 16050]

# required for cleanup
# Required for cleanup
actlog:
  mount_point: "TSMalog"
  lv: lv_actlog
  vg: vg_actlog

archlog:
  mount_point: "TSMarchlog"
  lv: lv_archlog
  vg: vg_archlog
