- name: Gather system facts
  ansible.builtin.setup:
  ignore_errors: true

# Java version (works on both AIX and Linux)
- name: Get Java version
  ansible.builtin.command: java -version 2>&1
  register: java_version_output
  ignore_errors: true
  changed_when: false

- name: Set Java version fact
  ansible.builtin.set_fact:
    java_version: "{{ java_version_output.stderr_lines[0] | default('Java is not installed') }}"

# -- Fallback for Memory Info if Ansible memory facts are missing --

- name: Fallback memory info (AIX) using prtconf
  ansible.builtin.command: prtconf | grep "Memory Size"
  register: aix_memory_output
  changed_when: false
  when: ansible_system == 'AIX'

- name: Extract memory size from AIX prtconf
  ansible.builtin.set_fact:
    aix_memory_mb: "{{ (aix_memory_output.stdout | regex_search('\\d+')).strip() }}"
  when: ansible_system == 'AIX' and aix_memory_output.rc == 0

# -- Set final system_info object with platform-safe defaults --

- name: Collect All System Information
  ansible.builtin.set_fact:
    system_info:
      architecture: "{{ ansible_architecture | default('unknown') }}"
      os_name: "{{ ansible_distribution | default(ansible_os_family | default('unknown')) }}"
      os_version: "{{ ansible_distribution_version | default(ansible_os_version | default('unknown')) }}"
      total_memory_mb: >-
        {{ ansible_memtotal_mb
            | default(ansible_memory_mb.real.total, true)
            | default(aix_memory_mb, true)
            | default('N/A') }}
      real_memory_mb: "{{ ansible_memory_mb.real.total | default('N/A') }}"
      free_memory_mb: "{{ ansible_memory_mb.real.free | default('N/A') }}"
      swap_total_mb: "{{ ansible_memory_mb.swap.total | default('N/A') }}"
      swap_free_mb: "{{ ansible_memory_mb.swap.free | default('N/A') }}"
      java_version: "{{ java_version }}"

- name: Show full system_info
  ansible.builtin.debug:
    var: system_info