# Default variables
# Operation to perform: backup, restore, query, delete

# Common vars ************************************************************************************

db2_operation: ""            # e.g: backup, restore, query, delete
db2_database: ""             # Name of the DB2 database to operate on
db2_user: ""                 # DB2 user for authentication (optional, required if using USER/PASSWORD in commands)
db2_password: ""             # DB2 password for authentication (optional)
db2_instance: ""             # Name of the DB2 instance to use (required for correct DB2 context)

# Backup-specific vars ***************************************************************************

# Partition (ON clause) variables
db2_backup_partition_on_type: ""          # e.g. DBPARTITIONNUM or DBPARTITIONNUMS
db2_backup_partition_on_all: false        # boolean, whether to use ALL keyword
db2_backup_partition_on_range: ""         # e.g. "1 TO 4"
db2_backup_partition_on_except: false     # boolean, whether to include EXCEPT clause
db2_backup_partition_on_except_type: ""   # e.g. DBPARTITIONNUM or DBPARTITIONNUMS
db2_backup_partition_on_except_range: ""  # e.g. "2 TO 3"

# Tablespace variables
db2_backup_tablespace: []                  # list of tablespaces
db2_backup_no_tablespace: false            # boolean, if true, NO TABLESPACE will be used

# Backup type and options
db2_backup_online: false
db2_backup_type: ""                        # e.g. INCREMENTAL, DELTA
db2_backup_use_tsm: true
db2_backup_open_sessions: 0                # integer number of sessions, 0 means not set
db2_backup_options: ""                      # additional options string
db2_backup_buffers: 0                       # number of buffers
db2_backup_buffer_size: 0                   # size of each buffer
db2_backup_parallelism: 0                   # parallelism value

# Compression clause
db2_backup_compress: false
db2_backup_comprlib: ""                     # compression library name
db2_backup_compropts: ""                     # compression options string

# Encryption clause
db2_backup_encrypt: false
db2_backup_encrlib: ""                       # encryption library name
db2_backup_encropts: ""                      # encryption options string

# Other options
db2_backup_util_impact_priority: ""         # e.g. LOW, MEDIUM, HIGH
db2_backup_include_logs: false
db2_backup_exclude_logs: false
db2_backup_without_prompting: false


# Restore-specific vars **************************************************************************

db2_restore_options: ""           # Any extra options for restore command
db2_restore_into: ""              # New database name for INTO (optional)
db2_restore_taken_at: ""          # Timestamp for TAKEN AT (optional)
db2_restore_replace_existing: false # Whether to replace existing database
db2_restore_without_rollforward: false # Whether to skip rollforward after restore
db2_restore_tablespaces: []       # List of tablespaces to restore (empty for all)
db2_restore_dbpartitions: ""      # List of database partitions to restore (optional)
db2_restore_parallelism: 4        # Number of parallel processes for restore
db2_restore_encrypt: false        # Whether to decrypt the backup during restore
db2_restore_encrlib: ''           # Encryption library for restore (optional)
db2_restore_encrpwd: ''           # Encryption password for restore (optional)
db2_restore_rollforward: true     # Whether to perform rollforward after restore
db2_restore_target_path: ""        # Source path for restore (optional, used for FROM clause)
db2_restore_logtarget: ""          # Log target directory for restore (optional, used for LOGTARGET clause)
db2_restore_buffer: ""             # Buffer size for restore (optional, used for BUFFER clause)


# Query-specific vars ****************************************************************************

db2_query_type: ""                       # Type: backup, log, tablespace, loadcopy
db2_query_backup_level: ""               # Backup level (for type=backup): full, incremental, delta, nonincremental
db2_query_show_inactive: false           # Show inactive backup images
db2_query_logs_between_start: ""         # e.g. 00000123
db2_query_logs_between_end: ""           # e.g. 00000456
db2_query_chain: ""                      # Log chain number Integer (e.g., 1, 2, 3)
db2_query_verbose: false                 # Whether to show verbose output
db2_query_dbname: ""                     # Database name (required for query)
db2_query_additional_options: ""         # e.g. "-ksprompt" or "complib libz.so"
db2_query_password: ""                   # TSM password
db2_query_nodename: ""                   # TSM node name
db2_query_owner: ""                      # Owner ID for TSM
db2_query_without_prompting: false       # Whether to disable prompting


# Delete-specific vars ***************************************************************************

db2_delete_type: ""               # Type of delete: FULL, INCREMENTAL, DELTA, TABLESPACE, etc.
db2_delete_tablespaces: []        # List of tablespaces to delete
db2_delete_keep: ""               # KEEP n backups
db2_delete_older_than: ""         # OLDER THAN timestamp or n days
db2_delete_taken_at: ""           # TAKEN AT timestamp
db2_delete_logs_between: ""       # LOGS BETWEEN sn1 AND sn2
db2_delete_chain: ""              # CHAIN n
db2_delete_options: ""            # Any extra options for delete command
