---
- name: Get the Storage Protect Server Facts
  sp_server_facts:
    server_name: "{{ server_name }}"
    username: "{{ dsm_user }}"
    password: "{{ dsm_pass }}"
    q_status: true
    q_monitorsettings: true
    q_db: false
    q_dbspace: true
    q_log: false
    q_domain: true
    q_copygroup: true
    q_replrule: false
    q_devclass: true
    q_mgmtclass: true
    q_stgpool: true
  register: result

- name: Display output
  debug:
    var: result
