---
- name: Prepare Storage for xsmall server
  hosts: "{{ target_hosts | default('all') }}"
  become: true
  roles:
    - ibm.storage_protect.storage_prepare
  vars:
    storage_prepare_size: "xsmall"
