# Default variables
# ==== installation and uninstallation vars =====
sp_server_state: "present"
profile_id: "IBM Storage Protect"
install_location: "/opt/IBM/InstallationManager/eclipse"
secure_port: "9443"
ssl_password: "YourSSLPassword"
ssl_password_confirm: "{{ ssl_password }}"
license_value: "tsm"
license_option: "A"
sp_server_install_dest: "/opt/sp_server_binary/"
sp_server_upgrade_dest: "/opt/sp_server_upgrade_binary"
sp_server_temp_dest: "{{ sp_server_upgrade_dest if sp_server_state == 'upgrade' else sp_server_install_dest }}"
repository_location: "{{ sp_server_temp_dest }}/repository"
db2_instance_path: "/opt/tivoli/tsm/db2/instance"
imcl_path: "/opt/IBM/InstallationManager/eclipse/tools/imcl"
sp_server_version: ""
sp_server_bin_repo: ""
sp_server_installation_status: false
# ==== tsm_user vars =====
tsm_group: "tsmusers"
tsm_group_gid: "10001"
tsm_user: "tsminst1"
tsm_user_uid: "10001"
tsm_user_password: "Tsmuser@@123456789"
sp_server_active_log_size: 17000
sp_server_action: "install"
offerings:
  server: true
#  license: true
  stagent: true
  devices: true
  oc: true
  ossm: true

# === configuration vars ======
#disk_device: /dev/sdb
#root_dir: /tsmroot
#directories:
#  - tsminst1
#  - tsmdb001
#  - tsmdb002
#  - tsmdb003
#  - tsmdb004
#  - tsmlog
#  - tsmarchlog
#  - tsmlogmirror
#  - tsmarchlogfailover

directories:
  - TSMdbspace01
  - TSMdbspace02
  - TSMdbspace03
  - TSMdbspace04
  - TSMalog
  - TSMarchlog

sp_server_compatible_architectures:
  - x86_64

server_size: 'xsmall'
act_log_size:
  xsmall: 24576
  small: 131072
  medium: 131072
  large: 524032

max_sessions:
  xsmall: 75
  small: 250
  medium: 500
  large: 1000

backup_start_time: "12:00"
backup_start_time_string: "12PM"
backup_start_plus_fourteen: "14:00"
maxcap: "100G"
dbbk_streams: "4"
dbbk_compress: "YES"
dbbk_password: "YourDBkPassword@@123456789"
backup_start_plus_ten: "10:00"
server_name: "Server1"
server_password: "IBMSPServer@@123456789"
server_blueprint: false
admin_name: "tsmuser1"
admin_password: "tsmuser1@@123456789"
