name: Run Ansible Playbook to Register Client

on:
  push:
    branches:
      - dev-gitops

jobs:
  run_ansible_playbook:
    runs-on: Self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python and Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install IBM Storage Protect Collection
        run: ansible-galaxy collection install ibm.storage_protect

      - name: Run Ansible Playbook to Register Client
        run: |
          ansible-playbook tests/integration/targets/client_node/test_sp_client.yml \
            -i localhost, \
             --extra-vars "{\"storage_protect_server_name\": \"***\", \"storage_protect_server_ip\": \"***\", \"storage_protect_username\": \"***\", \"storage_protect_password\": \"***\", \"client_name\": \"***\", \"client_password\": \"***\", \"client_policy_domain\": \"***\"}"
